### PR TITLE
Fix calling setCurrentStep after mounting of component

### LINKED ISSUE #35: React error trying to render extra fields in checkout
image

### PR DESCRIPTION
**Pull request by jaepass**
Went down the wrong direction debugging earlier but this fixes the rendering error and another shipping form error
Fixes #35

### CODE REVIEW

File: components/Checkout/ExtraFieldsForm.js [hunk 1]
```diff
@@ -19,7 +20,9 @@ function ExtraFieldsForm() {
   const { setCurrentStep, nextStepFrom } = useCheckoutDispatch();
 
   if (extrafields.length === 0) {
-    setCurrentStep(nextStepFrom("extrafields"));
+    useEffect(() => {
+      setCurrentStep(nextStepFrom("extrafields"));
+    }, [extrafields]);
     return null;
   }
```
Comment (ScopeyNZ) [inline components/Checkout/ExtraFieldsForm.js:27]: You'll need to move the condition inside of the `useEffect` call.

Comment (ScopeyNZ) [reply components/Checkout/ExtraFieldsForm.js]: Sorry I meant the `if (extrafields.length === 0)` needs to be inside the `useEffect` statement, as you can have side effects that happen depending on whether a condition passes, one of the rules of hooks.

Comment (jaepass) [reply components/Checkout/ExtraFieldsForm.js]: GAH sorry my bad i read it as "remove" not "move"

**Review by ScopeyNZ — APPROVED** [review]
