### PR TITLE
fix: show copy checkbox on collects.shipping_address

### LINKED ISSUE #19: Billing address has a "same as shipping" checkbox when I haven't entered a shipping address
image

No products have shipping enabled, so there's no shipping form. Hide the checkbox when `collects.shipping_address === false`

### PR DESCRIPTION
**Pull request by notrab**
Fixes #19

### CODE REVIEW

File: components/Checkout/BillingForm.js [hunk 1]
```diff
@@ -79,13 +80,15 @@ function BillingForm() {
...
           </legend>
 
-          <FormCheckbox
-            label="Same as shipping address"
-            name="billingIsShipping"
-            onChange={({ target: { checked } }) =>
-              checked && setValue("billing", shipping)
-            }
-          />
+          {collects.shipping_address && (
```
Comment (notrab) [inline components/Checkout/BillingForm.js:83]:
```suggestion
          {collects?.shipping_address && (
```

**Review by robbieaverill — APPROVED** [review]
